# Generated by Django 2.1.5 on 2019-03-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Address_Info',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(max_length=15)),
                ('custAge', models.IntegerField()),
                ('custBalance', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer_Info',
            },
        ),
    ]
